apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-config-server-deployment
  labels:
    app: backend-config-server-deployment
spec:
  selector:
    matchLabels:
      app: backend-config-server-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-config-server-deployment
    spec:
      containers:
        - name: pep2-backend-config-server
          image: jaramillo1337/pep2-backend-config-server:latest
          ports:
            - containerPort: 8081
---

apiVersion: v1
kind: Service
metadata:
  name: backend-config-server
  labels:
    app: backend-config-server
spec:
  selector:
    app: backend-config-server-deployment
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer