apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres-config-map
data:
  POSTGRES_DB_HOST: postgres
  #base de dato Resumen
  POSTGRES_DB_RESUMEN: resumen
  #base de dato Estudiantes
  POSTGRES_DB_ESTUDIANTE: estudiantes
  #base de dato Archivos
  POSTGRES_DB_ARCHIVO: archivos