apiVersion: apps/v1
kind: Deployment
metadata:
  name: subir-archivo-deployment
  labels:
    app: subir-archivo-deployment
spec:
  selector:
    matchLabels:
      app: subir-archivo-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: subir-archivo-deployment
    spec:
      containers:
        - name: pep2-subir-archivo
          image: jaramillo1337/pep2-subir-archivo:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://backend-config-service:8081
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://backend-eureka-service:8761
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: POSTGRES_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_HOST
            - name: POSTGRES_DB_ARCHIVO
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_ARCHIVO
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: subir-archivo
  labels:
    app: subir-archivo
spec:
  selector:
    app: subir-archivo-deployment
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer
